app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core"))
]

app/core/urls.py
from django.urls import path

from .views import (
    HomePageView,
    RegisterView,
    LoginView,
    LogoutView,
    URLCreateView,
    URLDeleteView,
    URLUpdateView,
    RedirectURLView,
    StatsPageView,
)


app_name = "core"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("createURL/", URLCreateView.as_view(), name="create-url"),
    path("deleteURL/<str:shortened_url>", URLDeleteView.as_view(), name="delete-url"),
    path("updateURL/<str:shortened_url>", URLUpdateView.as_view(), name="update-url"),
    path("<str:shortened_url>", RedirectURLView.as_view(), name="redirect"),
    path("stats/", StatsPageView.as_view(), name="stats"),

]

app/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import URLValidator
from django.utils import timezone
from django.utils.text import slugify

import random
import string


# Creating URL model
class URLData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    url = models.CharField(
        max_length=255,
        validators=[
            URLValidator(message="Lütfen Geçerli Bir URL girin. (ex: https://example.com)")
        ],
    )
    shortened_url = models.CharField(max_length=10, unique=True, blank=True)
    click_count = models.PositiveIntegerField(default=0, editable=False)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    last_click_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.shortened_url

    def increment_click_count(self):
        self.click_count += 1
        self.save()

    def save(self, *args, **kwargs):
        if not self.shortened_url:
            self.shortened_url = "".join(
                random.choices(string.ascii_letters, k=random.randint(3, 8))
            )

        self.shortened_url = slugify(self.shortened_url)

        super().save(*args, **kwargs)

app/core/forms.py
from django.forms import ModelForm, TextInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import URLData


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email"]
        widgets = {
            "username": TextInput(attrs={"placeholder": "Username"}),
            "email": TextInput(attrs={"placeholder": "Email"}),
        }


class URLDataForm(ModelForm):
    class Meta:
        model = URLData
        exclude = ("user", "shortened_url")
        widgets = {
            "url": TextInput(attrs={"placeholder": "Url"}),
        }


class URLUpdateForm(ModelForm):
    class Meta:
        model = URLData
        exclude = ("user",)

app/core/views.py
from django.shortcuts import render, redirect

from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from django.views import View

from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse_lazy

from django.utils.decorators import method_decorator

from .forms import UserRegisterForm, URLDataForm, URLUpdateForm
from .models import URLData

from matplotlib import pyplot as plt
from io import BytesIO
import base64
import random


@method_decorator(login_required(login_url=reverse_lazy("core:login")), name="dispatch")
class HomePageView(TemplateView):
    template_name = "home.html"

    def get(self, request, *args, **kwargs):
        search_term = request.GET.get("search")
        urls = URLData.objects.filter(user=request.user)
        if search_term:
            urls = urls.filter(url__icontains=search_term)
        context = self.get_context_data(urls=urls)
        return self.render_to_response(context)


class RegisterView(CreateView, SuccessMessageMixin):
    model = User
    template_name = "register.html"
    form_class = UserRegisterForm
    success_message = "Your user was created successfully"
    success_url = reverse_lazy("core:login")


class LoginView(LoginView):
    template_name = "login.html"

    def form_valid(self, form):
        messages.info(self.request, f"You are now logged in as {form.cleaned_data['username']}")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Invalid username or password.")
        return super().form_invalid(form)


class LogoutView(LogoutView):
    next_page = reverse_lazy("core:home")
    template_name = "logout.html"


class URLCreateView(CreateView, LoginRequiredMixin):
    model = URLData
    template_name = "create_url.html"
    form_class = URLDataForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(URLCreateView, self).dispatch(*args, **kwargs)


class URLUpdateView(UpdateView, LoginRequiredMixin):
    model = URLData
    form_class = URLUpdateForm
    template_name = "update_url.html"
    success_url = reverse_lazy("core:home")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(URLUpdateView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        shortened_url = self.kwargs.get("shortened_url")
        return URLData.objects.get(shortened_url=shortened_url)


class URLDeleteView(DeleteView):
    model = URLData
    template_name = "delete_url.html"
    success_url = reverse_lazy("core:home")

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(URLDeleteView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        shortened_url = self.kwargs.get("shortened_url")
        return URLData.objects.get(shortened_url=shortened_url)


# Redirect to Original URL
class RedirectURLView(View):
    def get(self, request, shortened_url):
        url_data = URLData.objects.filter(shortened_url=shortened_url).first()
        if url_data:
            url_data.increment_click_count()

            return redirect(url_data.url)
        return redirect("core:home")


class StatsPageView(TemplateView):
    template_name = "stats.html"

    def get(self, request):
        user = request.user
        url_data = URLData.objects.filter(user=user)
        click_counts = [data.click_count for data in url_data]
        shortened_urls = [data.shortened_url for data in url_data]

        colors = []
        for _ in range(len(url_data)):
            r = random.random()
            g = random.random()
            b = random.random()
            colors.append((r, g, b))

        plt.bar(shortened_urls, click_counts, color=colors)
        plt.xlabel("Shortened URL")
        plt.ylabel("Click")
        plt.title("URL Click Statistics")

        buf = BytesIO()
        plt.savefig(buf, format="png")
        buf.seek(0)
        graph_img = buf.getvalue()
        buf.close()

        graph_img_base64 = base64.b64encode(graph_img).decode("utf-8")

        context = {"graph_img": graph_img_base64}

        return render(request, self.template_name, context)

app/templates/create_url.html
{% extends "partials/_base.html" %} {% load widget_tweaks %}
{% block title %}New URL{% endblock title %}{% block content %}

<div class="container pt-5 d-flex justify-content-center">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:"form-control" }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
    <div class="form-group pt-2">
      <input value="Add" type="submit" class="btn btn-success">
      <a href="{% url 'core:home' %}" class="btn btn-warning">Cancel</a>
    </div>
  </form>
</div>

{% endblock content %}

app/templates/delete_url.html
{% extends "partials/_base.html" %} {% load widget_tweaks %}
{% block title %}Confirm{% endblock title %}
{% block content %}

<div class="container pt-5">
  <form method="post" novalidate>
    {% csrf_token %}
      <p>The URL <b>{{ object }}</b>, If you have completed it will be removed from your list. Do you want to continue?</p>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
</div>

{% endblock content %}

app/templates/home.html
{% extends "partials/_base.html" %}
{% block content %}
    <div class="container">
        {% if urls %}
        <h1 class="mt-5 text-center">URLS</h1>
        <div class="d-flex justify-content-between mt-3" >
            <form method="GET" class="form-inline">
                <div class="d-flex">
                    <input style="width:200px" class="form-control" type="text" name="search" placeholder="URL" aria-label="Search" />
                    <button class="btn btn-outline-success mx-2" type="submit">Search </button>
                </div>
            </form>

            </form>
            <a href="{% url 'core:create-url' %}" class="btn btn-success mb-5" role="button">
            <span class="glyphicon glyphicon-">Create URL</span></a>
        </div>
        
        <div class="" style="height: 250px;">
            <table class="table table-warning">
                <thead>
                    <tr>
                        <th scope="col">User</th>
                        <th scope="col">URL</th>
                        <th scope="col">Shortened URL</th>
                        <th>Create Date</th>
                        <th>Last Click Date</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for url in urls %}
                        <tr>
                            <td>{{ url.user }}</td>
                            <td>{{ url.url }}</td>
                            <td><a href="{{ url.shortened_url }}" target="_blank">{{ url.shortened_url }}</a></td>
                            <td>{{ url.created_at }}</td>
                            <td>{{ url.last_click_at }}</td>
                            <td><a class="btn btn-primary"href="{% url 'core:update-url' url.shortened_url %}">Update</a></td>
                            <td><a class="btn btn-danger"href="{% url 'core:delete-url' url.shortened_url %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>        
        {% else %}
        <div class="mt-5">
            <h1 class="text-center" style="color:red;">You have not created any URLs</h1>
            <div class="d-flex justify-content-center mt-3" >
                <a href="{% url 'core:create-url' %}" class="btn btn-success mb-5" role="button">
                <span class="glyphicon glyphicon-">Create URL</span></a>
            </div>
        </div>
        </div>
        
        {% endif %}
    </div>
{% endblock content %}

app/templates/login.html
{% extends "partials/../partials/_base.html" %} {% load widget_tweaks %}
{% block title %}Register{% endblock title %}{% block content %}

<div class="container pt-5 d-flex justify-content-center">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:"form-control" }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
    <div class="form-group py-2">
      <input value="Login" type="submit" class="btn btn-success">
    </div>
    Don't have an account? <a href="{% url 'core:register' %}"><strong>register here</strong></a>!
  </form>
</div>

{% endblock content %}

app/templates/logout.html
{% extends "partials/../partials/_base.html" %} {% load widget_tweaks %}
{% block title %}Logout{% endblock title %}{% block content %}

{% if request.user.is_authenticated %}
    <div class="text-center my-5">
        <form method='POST'>{% csrf_token %}
            <p>Are You Sure?</p>
            <button type='submit' class='btn btn-danger '>Yes</button>
        </form>
    </div>
{% else %}
<p class="mx-5 my-3">You have not log in yet <a href='/login/'>Login</a></p>
{% endif %}


{% endblock content %}

app/templates/partials/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock title %}</title>
</head>
<body>

{% include "partials/_navbar.html" %}

{% block content %}

{% endblock content %}
</body>
</html>

app/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'core:home' %}" style="margin-left: 25px;">URLS SERVICE</a>
  
    <div class="navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <a class="nav-link btn btn-outline-secondary mx-2" href="{% url 'core:stats' %}">Statistics</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-danger" href="{% url 'core:logout' %}">Logout</a>
        </li>
      </ul>
      {% else %}
      {% endif %}
    </div>
  </nav>
  

app/templates/register.html
{% extends "partials/../partials/_base.html" %} {% load widget_tweaks %}
{% block title %}Register{% endblock title %}{% block content %}

<div class="container pt-5 d-flex justify-content-center">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:"form-control" }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
    <div class="form-group py-2">
      <input value="Register" type="submit" class="btn btn-success">
      <a href="{% url 'core:home' %}" class="btn btn-warning">Cancel</a>
    </div>
    Already have an account? <a href="{% url 'core:login' %}"><strong>login here</strong></a>!
  </form>
</div>

{% endblock content %}

app/templates/stats.html
{% extends "partials/_base.html" %}
{% block content %}
    <div class="container">
        <h1 class="mt-5 text-center">Statistics</h1>
        <div class="d-flex align-items-center justify-content-center mt-4" style="height: 500px;">
            <img src="data:image/png;base64,{{ graph_img }}" alt="Count">
        </div>
    </div>
{% endblock content %}

app/templates/update_url.html
{% extends "partials/_base.html" %} {% load widget_tweaks %}
{% block title %}Update URL{% endblock title %}
{% block content %}

<div class="container pt-5 d-flex justify-content-center">
  <form method="post" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:"form-control" }}
        {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
  <div class="form-group d-flex justify-content-end mt-2">
        <button type="submit" class="btn btn-success">
          <span class="glyphicon glyphicon-ok">Update</span>
        </button>
    </div>
  </form>
</div>

{% endblock content %}